site_name: Larka Project
theme:
  logo: img/images.png

  features:
    - content.code.copy
    - navigation.tabs
    - navigation.prune
    - navigation.indexes
    - navigation.sevtions
    - search.suggest
    - search.highlight

  name: material

  palette:
   primary: red

extra:
  social:
  - icon: fontawesome/brands/instagram
    link: https://www.instagram.com/larka1791/?hl=id